use_frameworks!

platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'CheckLoginModule_Example' do
  pod 'CheckLoginModule', :path => '../'
  
  
  pod 'SnapKit'
  pod 'Masonry'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'KRProgressHUD'
  
  #解决Xcode14.3移除ARC相关的库导致Build报错【https://blog.csdn.net/crasowas/article/details/129901398】
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end

  target 'CheckLoginModule_Tests' do
    inherit! :search_paths

    
  end
end
